server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gyaanbyte_prod
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
